name: Deploy Cookie API to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Cookie API
        env:
          SERVER: ${{ secrets.SERVER_IP }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh-keyscan $SERVER >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no $USER@$SERVER << 'EOF'
            cd /home/neutrino_cookie_api
            git pull origin main
            go mod tidy
            
            # Check Redis status and restart if needed
            if ! systemctl is-active --quiet redis-server; then
                sudo systemctl start redis-server
            fi
            
            # Restart PM2 app
            pm2 restart neutrino_cookie_api || pm2 start ecosystem.config.js --only neutrino_cookie_api
            pm2 save
          EOF
